[package]
edition = "2021"
name = "woof"
version = "0.1.0"

[dependencies]
actix-web = "4.0.1"
anyhow = "1.0.56"
dotenv = "0.15.0"
sea-orm = { version = "0.7.1", features = ["sqlx-postgres", "runtime-actix-rustls"] }
serde = { version = "1.0.136", features = ["derive"] }
uuid = "0.8.2"
