//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

pub use super::comments::Entity as Comments;
pub use super::posts::Entity as Posts;
pub use super::users::Entity as Users;
pub use super::votes::Entity as Votes;
